In [1]:
import torch

# initialize tensors

In [2]:
# uninitialized matrix
x = torch.empty(6, 4)
print(x)

tensor([[-5.0861e-11,  4.5828e-41, -5.0861e-11,  4.5828e-41],
        [-5.0861e-11,  4.5828e-41, -4.9992e-11,  4.5828e-41],
        [ 0.0000e+00,  0.0000e+00, -2.1144e-01,  4.5828e-41],
        [-2.1143e-01,  4.5828e-41,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [3]:
# randomly initialized matrix
x = torch.rand(6, 4)
print(x)

tensor([[0.9139, 0.9390, 0.0870, 0.9506],
        [0.7614, 0.5523, 0.5183, 0.0493],
        [0.0025, 0.8013, 0.4986, 0.0188],
        [0.7609, 0.4133, 0.4834, 0.9839],
        [0.5211, 0.9298, 0.5479, 0.0975],
        [0.3057, 0.0737, 0.2030, 0.9013]])


In [4]:
# zero filled matrix
x = torch.zeros(6, 4, dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [5]:
# construct tensor from data
x = torch.tensor([[5.5, 3],
                  [7.2, 0]])
print(x)

tensor([[5.5000, 3.0000],
        [7.2000, 0.0000]])


In [6]:
# create tensor from existing tesfor and 
# reuse the properties of input tensor

# new_* for overriding size
x = x.new_ones(5, 4, dtype=torch.double)
print(x)

# override dtype but same size
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0935, -0.0233, -0.2894, -0.9183],
        [ 1.2784, -0.3687,  2.3859, -0.2566],
        [ 0.3517,  2.3991, -0.5067, -0.2271],
        [-1.0266,  0.4553, -0.1353,  1.5288],
        [ 0.9630,  0.8329, -0.0540, -0.7559]])


In [7]:
# return size of the matrix in tuple
print(x.size())

torch.Size([5, 4])


# operations with tensors

In [8]:
# adding
y = torch.rand(5, 4)
print(x + y)
print(torch.add(x, y))

tensor([[-1.5471e-03,  3.2460e-02, -1.6050e-01, -4.2789e-01],
        [ 1.4770e+00,  1.0100e-01,  2.8919e+00,  3.2946e-01],
        [ 9.3317e-01,  2.4001e+00,  3.4011e-01,  6.1315e-01],
        [-7.7513e-01,  9.7870e-01,  6.2150e-01,  1.8648e+00],
        [ 1.8456e+00,  1.0284e+00,  8.6296e-01, -4.7060e-01]])
tensor([[-1.5471e-03,  3.2460e-02, -1.6050e-01, -4.2789e-01],
        [ 1.4770e+00,  1.0100e-01,  2.8919e+00,  3.2946e-01],
        [ 9.3317e-01,  2.4001e+00,  3.4011e-01,  6.1315e-01],
        [-7.7513e-01,  9.7870e-01,  6.2150e-01,  1.8648e+00],
        [ 1.8456e+00,  1.0284e+00,  8.6296e-01, -4.7060e-01]])


In [9]:
result = torch.empty(5, 4)
torch.add(x, y, out=result)
print(result)

result = torch.add(x, y)
print(result)

tensor([[-1.5471e-03,  3.2460e-02, -1.6050e-01, -4.2789e-01],
        [ 1.4770e+00,  1.0100e-01,  2.8919e+00,  3.2946e-01],
        [ 9.3317e-01,  2.4001e+00,  3.4011e-01,  6.1315e-01],
        [-7.7513e-01,  9.7870e-01,  6.2150e-01,  1.8648e+00],
        [ 1.8456e+00,  1.0284e+00,  8.6296e-01, -4.7060e-01]])
tensor([[-1.5471e-03,  3.2460e-02, -1.6050e-01, -4.2789e-01],
        [ 1.4770e+00,  1.0100e-01,  2.8919e+00,  3.2946e-01],
        [ 9.3317e-01,  2.4001e+00,  3.4011e-01,  6.1315e-01],
        [-7.7513e-01,  9.7870e-01,  6.2150e-01,  1.8648e+00],
        [ 1.8456e+00,  1.0284e+00,  8.6296e-01, -4.7060e-01]])


In [10]:
# inplace on y
y.add_(x)
print(y)

tensor([[-1.5471e-03,  3.2460e-02, -1.6050e-01, -4.2789e-01],
        [ 1.4770e+00,  1.0100e-01,  2.8919e+00,  3.2946e-01],
        [ 9.3317e-01,  2.4001e+00,  3.4011e-01,  6.1315e-01],
        [-7.7513e-01,  9.7870e-01,  6.2150e-01,  1.8648e+00],
        [ 1.8456e+00,  1.0284e+00,  8.6296e-01, -4.7060e-01]])


In [11]:
## indexing

print(x[:, 1])

tensor([-0.0233, -0.3687,  2.3991,  0.4553,  0.8329])


In [12]:
## resizing

x = torch.randn(4, 6)
print(x.size())

y = x.view(2, 12)
print(y.size())

# size -1 is determined by the other dimension
# thus, here it will be 24/8 = 3
z = x.view(-1, 8) 
print(z.size())

torch.Size([4, 6])
torch.Size([2, 12])
torch.Size([3, 8])


In [13]:
## returning one element tensor as python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.7840])
-1.7839534282684326


# Tensor2Numpy , Numpy2Tensor

In [14]:
a = torch.ones(6)
print(a)

tensor([1., 1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)  # change reflected

tensor([2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2.]


In [17]:
# numpy2tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# to cuda tensor

```
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
```